expose_php = Off
memory_limit = 1024M
max_execution_time = 120
max_input_time = 120
max_input_vars = 5000
post_max_size = 64M
upload_max_filesize = 64M
default_socket_timeout = 120
date.timezone = UTC

display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2

realpath_cache_size = 4096K
realpath_cache_ttl = 600

session.cookie_httponly = 1
session.use_strict_mode = 1
