<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Fee Structure</title>
    <style>
        /* Minimal by design: thin rules, no fills, one accent line under the
           masthead. Note for dompdf — no universal margin reset here, it would
           wipe the @page margins and bleed the sheet to the paper edge. */
        @page { margin: 30px 34px; }

        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11px; color: #111827; line-height: 1.45; }

        .head { border-bottom: 1px solid #111827; padding-bottom: 9px; margin-bottom: 4px; }
        .head .school { font-size: 15px; font-weight: bold; letter-spacing: .4px; text-transform: uppercase; }
        .head .meta { font-size: 8.5px; color: #6b7280; margin-top: 2px; }

        .title { font-size: 10px; letter-spacing: 1.6px; text-transform: uppercase; color: #6b7280;
                 margin: 14px 0 2px; }
        .scope { font-size: 12px; font-weight: bold; }
        .stamp { font-size: 8.5px; color: #9ca3af; margin-top: 1px; margin-bottom: 16px; }

        .grp { margin-bottom: 18px; }
        .grp-head { font-size: 11px; font-weight: bold; padding-bottom: 4px; border-bottom: 1px solid #111827; }
        .grp-head span { float: right; font-weight: normal; color: #6b7280; }

        table.fs { width: 100%; border-collapse: collapse; }
        table.fs th { font-size: 8px; letter-spacing: .7px; text-transform: uppercase; color: #9ca3af;
                      text-align: left; padding: 6px 0 5px; border-bottom: 1px solid #e5e7eb; font-weight: normal; }
        table.fs td { padding: 5px 0; border-bottom: 1px solid #f3f4f6; font-size: 10.5px; }
        table.fs td.num, table.fs th.num { text-align: right; }
        table.fs td.sl { color: #9ca3af; font-size: 9px; }
        tr.tot td { border-top: 1px solid #111827; border-bottom: 0; padding-top: 6px; font-weight: bold; }

        .grand { margin-top: 6px; border-top: 2px solid #111827; padding-top: 7px; font-size: 12px; font-weight: bold; }
        .grand span { float: right; }

        .foot { margin-top: 22px; padding-top: 7px; border-top: 1px solid #e5e7eb;
                font-size: 8px; color: #9ca3af; text-align: center; letter-spacing: .3px; }

        .empty { text-align: center; color: #9ca3af; padding: 34px 0; font-size: 11px; }

        .toolbar { text-align: center; margin: 20px 0 0; }
        .toolbar button { padding: 8px 20px; background: #111827; color: #fff; border: 0; border-radius: 6px;
                          cursor: pointer; font-size: 12px; letter-spacing: .3px; }
        @media print { .toolbar { display: none; } }
    </style>
</head>
<body>

    <div class="head">
        <div class="school">{{ $org->name ?? 'School' }}</div>
        <div class="meta">
            {{ $org->address ?? '' }}
            @if (!empty($org?->mobile_number)) · {{ $org->mobile_number }} @endif
            @if (!empty($org?->email)) · {{ $org->email }} @endif
        </div>
    </div>

    <div class="title">Academic Fee Structure</div>
    <div class="scope">{{ $filterLabel ?: 'All Classes' }}</div>
    <div class="stamp">Generated {{ $generatedAt->format('d M Y, g:i A') }}</div>

    @forelse ($groups as $g)
        <div class="grp">
            <div class="grp-head">
                {{ $g['class'] }} — {{ $g['section'] }}
                <span>{{ $g['year'] }}</span>
            </div>
            <table class="fs">
                <thead>
                    <tr>
                        <th style="width:26px;">#</th>
                        <th>Fee Name</th>
                        <th class="num" style="width:100px;">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($g['rows'] as $i => $r)
                        <tr>
                            <td class="sl">{{ $i + 1 }}</td>
                            <td>{{ $r->fee_name }}</td>
                            <td class="num">{{ number_format($r->amount, 2) }}</td>
                        </tr>
                    @endforeach
                    <tr class="tot">
                        <td colspan="2">Total</td>
                        <td class="num">{{ number_format($g['total'], 2) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    @empty
        <p class="empty">No academic fee structure found.</p>
    @endforelse

    @if ($groups->count() > 1)
        <div class="grand">Grand Total <span>{{ number_format($grandTotal, 2) }}</span></div>
    @endif

    <div class="foot">All amounts in INR · System-generated by {{ $org->name ?? 'the school' }}</div>

    @if (!empty($printable))
        <div class="toolbar"><button onclick="window.print()">Print / Save as PDF</button></div>
    @endif
</body>
</html>
