<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Transport Fee Structure</title>
    <style>
        /* Same minimal sheet as the academic structure. No universal margin
           reset — that would wipe the @page margins under dompdf. */
        @page { margin: 30px 34px; }

        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11px; color: #111827; line-height: 1.45; }

        .head { border-bottom: 1px solid #111827; padding-bottom: 9px; }
        .head .school { font-size: 15px; font-weight: bold; letter-spacing: .4px; text-transform: uppercase; }
        .head .meta { font-size: 8.5px; color: #6b7280; margin-top: 2px; }

        .title { font-size: 10px; letter-spacing: 1.6px; text-transform: uppercase; color: #6b7280;
                 margin: 14px 0 2px; }
        .scope { font-size: 12px; font-weight: bold; }
        .stamp { font-size: 8.5px; color: #9ca3af; margin-top: 1px; margin-bottom: 16px; }

        table.info { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.info td { font-size: 10px; padding: 3px 0; }
        table.info td.k { color: #9ca3af; width: 110px; text-transform: uppercase; font-size: 8px; letter-spacing: .7px; }

        table.mo { width: 100%; border-collapse: collapse; }
        table.mo th { font-size: 8px; letter-spacing: .7px; text-transform: uppercase; color: #9ca3af;
                      text-align: left; padding: 6px 0 5px; border-bottom: 1px solid #111827; font-weight: normal; }
        table.mo td { padding: 5px 0; border-bottom: 1px solid #f3f4f6; font-size: 10.5px; }
        table.mo td.num, table.mo th.num { text-align: right; }
        table.mo td.sl { color: #9ca3af; font-size: 9px; }
        td.free { color: #9ca3af; }
        tr.tot td { border-top: 1px solid #111827; border-bottom: 0; padding-top: 6px; font-weight: bold; }

        .foot { margin-top: 22px; padding-top: 7px; border-top: 1px solid #e5e7eb;
                font-size: 8px; color: #9ca3af; text-align: center; letter-spacing: .3px; }

        .toolbar { text-align: center; margin: 20px 0 0; }
        .toolbar button { padding: 8px 20px; background: #111827; color: #fff; border: 0; border-radius: 6px;
                          cursor: pointer; font-size: 12px; letter-spacing: .3px; }
        @media print { .toolbar { display: none; } }
    </style>
</head>
<body>

    <div class="head">
        <div class="school">{{ $org->name ?? 'School' }}</div>
        <div class="meta">
            {{ $org->address ?? '' }}
            @if (!empty($org?->mobile_number)) · {{ $org->mobile_number }} @endif
            @if (!empty($org?->email)) · {{ $org->email }} @endif
        </div>
    </div>

    <div class="title">Transport Fee Structure</div>
    <div class="scope">{{ $route->route_name }}</div>
    <div class="stamp">Generated {{ $generatedAt->format('d M Y, g:i A') }}</div>

    <table class="info">
        <tr><td class="k">Driver</td><td>{{ $route->driver->user->name ?? 'No driver' }}</td></tr>
        <tr><td class="k">Pickup Time</td><td>{{ $route->pickup_time ?: '—' }}</td></tr>
        <tr><td class="k">Monthly Fee</td><td>{{ number_format($route->monthly_fee, 2) }}</td></tr>
        <tr><td class="k">Status</td><td>{{ $route->is_active ? 'Active' : 'Inactive' }}</td></tr>
    </table>

    <table class="mo">
        <thead>
            <tr>
                <th style="width:26px;">#</th>
                <th>Month</th>
                <th class="num" style="width:110px;">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($months as $i => $m)
                <tr>
                    <td class="sl">{{ $i + 1 }}</td>
                    <td class="{{ $m['free'] ? 'free' : '' }}">{{ $m['month'] }}@if ($m['free']) — free @endif</td>
                    <td class="num {{ $m['free'] ? 'free' : '' }}">{{ number_format($m['amount'], 2) }}</td>
                </tr>
            @endforeach
            <tr class="tot">
                <td colspan="2">Annual Total</td>
                <td class="num">{{ number_format($annualTotal, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="foot">All amounts in INR · System-generated by {{ $org->name ?? 'the school' }}</div>

    @if (!empty($printable))
        <div class="toolbar"><button onclick="window.print()">Print / Save as PDF</button></div>
    @endif
</body>
</html>
