<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Seeds the official SUPERLMS Terms and Conditions (25 separate sections, one
 * per numbered section of the legal document) into the term_and_conditions
 * table. Only the sections are replaced — any additional_info entries or
 * uploaded files already stored in metadata are preserved, and the super-admin
 * panel keeps full edit control afterwards.
 *
 * Section headings intentionally carry no numbers: both the super-admin view
 * and the public /web/terms-conditions page number sections automatically by
 * position.
 */
return new class extends Migration
{
    public function up(): void
    {
        $row = DB::table('term_and_conditions')->orderBy('id')->first();

        $metadata = $row ? (json_decode($row->metadata, true) ?: []) : [];
        $metadata['sections'] = $this->sections();

        $data = [
            'platform_name' => 'SUPERLMS',
            'company_name'  => 'Super Learnings Private Limited',
            'metadata'      => json_encode($metadata, JSON_UNESCAPED_UNICODE),
            'last_updated'  => '2026-07-07',
            'updated_at'    => now(),
        ];

        if ($row) {
            DB::table('term_and_conditions')->where('id', $row->id)->update($data);
        } else {
            DB::table('term_and_conditions')->insert($data + ['created_at' => now()]);
        }
    }

    public function down(): void
    {
        // Content seed — nothing sensible to roll back to.
    }

    private function sections(): array
    {
        return [
            ['head' => 'Introduction', 'desc' => <<<'TXT'
SUPERLMS is a product of Super Learnings Private Limited.
Website: www.superlms.in
Registered Office: Office No. 02, Braj Vihar Colony, Jattari, Khair, Aligarh, Uttar Pradesh – 202137
Email: support@superlms.in | Phone: +91 9084748563
Effective Date: 07 July 2026

These Terms and Conditions ("Terms") constitute a legally binding agreement between Super Learnings Private Limited ("Company", "SuperLMS", "We", "Us", "Our") and any School, educational institution, administrator, teacher, staff member, student, parent/guardian, or other individual/entity ("You", "User") who accesses or uses the SuperLMS website, mobile applications, Admin Panel, APIs, or any related services (collectively, the "Platform" or "Services").

By registering for, accessing, or using the Platform, You agree to be bound by these Terms, Our Privacy Policy, and any other policies referenced herein. If You do not agree to these Terms, You must not access or use the Platform.

Where the Platform is used by a School on behalf of its students, teachers, staff, and parents, the School is responsible for ensuring that all such Users are made aware of, and agree to, these Terms prior to being onboarded.

These Terms are governed in accordance with applicable Indian laws, including but not limited to:
• The Indian Contract Act, 1872;
• The Information Technology Act, 2000 and rules framed thereunder;
• The Digital Personal Data Protection Act, 2023;
• The Consumer Protection Act, 2019 and the Consumer Protection (E-Commerce) Rules, 2020, to the extent applicable;
• The Copyright Act, 1957, and the Trade Marks Act, 1999, in respect of intellectual property;
• The Payment and Settlement Systems Act, 2007, and applicable RBI guidelines, in respect of online payment processing;
• The Right of Children to Free and Compulsory Education Act, 2009, and applicable CBSE/State Education Board regulations, to the extent relevant to School operations; and
• Any other applicable central or state legislation.
TXT],

            ['head' => 'Definitions', 'desc' => <<<'TXT'
• "Platform" means the SuperLMS website, mobile applications, Admin Panel, Teacher/Student/Parent dashboards, APIs, and all associated Services.
• "Institutional Client" / "School" means the school or educational institution that has subscribed to the Platform under a Service Agreement.
• "Authorised User" means any Teacher, Staff, Student, Parent/Guardian, or Administrator granted access to the Platform by the Institutional Client.
• "Content" means all data, text, images, documents, question banks, assessments, reports, and other materials uploaded to, generated by, or made available through the Platform.
• "Subscription" means the paid or trial access granted to an Institutional Client to use the Platform for a defined period.
• "Force Majeure Event" has the meaning given in the "Force Majeure" section of these Terms.
TXT],

            ['head' => 'Eligibility and Account Registration', 'desc' => <<<'TXT'
1. The Platform is intended primarily for use by Schools and their Authorised Users. Individuals below the age of 18 years ("minors") may access the Platform only as Students, under the supervision of their School and with the consent of their parent/guardian, and shall not independently register an account.
2. Schools registering on the Platform must provide accurate, current, and complete information, including registration/affiliation details, and must promptly update any change in such information.
3. Each Authorised User is responsible for maintaining the confidentiality of their login credentials (username, password, OTP) and for all activities that occur under their account. Users must immediately notify SuperLMS at support@superlms.in of any unauthorised use of their account.
4. SuperLMS reserves the right to refuse registration, suspend, or terminate any account that provides false, inaccurate, or misleading information, or that is used in violation of these Terms.
TXT],

            ['head' => 'Nature of Services', 'desc' => <<<'TXT'
SuperLMS provides a cloud-based School Learning Management System, including but not limited to the following modules:
• Student admission, attendance, and timetable management;
• Fee management and online/offline fee collection;
• Assignments, homework, quizzes, and online examinations;
• Report cards, certificates, and academic progress tracking;
• Communication tools (SMS, Email, WhatsApp, in-app notifications);
• Analytics and performance dashboards;
• AI-assisted learning recommendations, question generation, and automated feedback (see the "AI-Enabled Features — Disclaimer" section); and
• Integrations with third-party payment gateways, video-conferencing tools, and communication service providers.

SuperLMS reserves the right to modify, add, or discontinue any feature or module of the Platform at its sole discretion, with reasonable prior notice to Institutional Clients where such change materially affects the Services.
TXT],

            ['head' => 'AI-Enabled Features — Disclaimer', 'desc' => <<<'TXT'
Certain features of the Platform utilise Artificial Intelligence to assist with question generation, assignment evaluation, personalised learning recommendations, and performance insights. Users acknowledge and agree that:
1. AI-generated content and recommendations are intended solely as an aid to teachers, administrators, and students, and do not constitute final academic, disciplinary, or evaluative decisions;
2. All AI-generated output must be reviewed and validated by a qualified teacher or authorised School official before being relied upon or communicated to students/parents; and
3. SuperLMS makes no warranty as to the completeness, accuracy, or suitability of AI-generated content for any specific curriculum, examination board, or academic purpose.
TXT],

            ['head' => 'School/Institutional Client Obligations', 'desc' => <<<'TXT'
Each Institutional Client agrees to:
1. Obtain necessary consent from students, parents/guardians, and staff prior to onboarding them onto the Platform, in accordance with applicable data protection law, including the DPDP Act, 2023;
2. Ensure that data uploaded to the Platform (student records, staff records, academic data) is accurate and lawfully obtained;
3. Designate one or more Super Admin(s) responsible for user management, access control, and compliance with these Terms within the institution;
4. Use the Platform only for legitimate educational and administrative purposes, and not for any unlawful, defamatory, or harmful purpose;
5. Ensure that its Authorised Users comply with these Terms and with Our Privacy Policy; and
6. Promptly notify SuperLMS of any suspected data breach, unauthorised access, or misuse of the Platform.
TXT],

            ['head' => 'User Conduct and Acceptable Use', 'desc' => <<<'TXT'
Users agree not to:
1. Use the Platform for any unlawful purpose or in violation of any applicable law, including the IT Act, 2000;
2. Upload, transmit, or share any content that is obscene, defamatory, discriminatory, infringing, or harmful to minors;
3. Attempt to gain unauthorised access to any part of the Platform, other Users' accounts, or SuperLMS's servers/networks;
4. Introduce viruses, malware, or any code designed to disrupt or damage the Platform;
5. Reverse-engineer, decompile, or attempt to extract the source code of the Platform, except as permitted by law;
6. Use automated means (bots, scrapers) to access or extract data from the Platform without prior written consent;
7. Misrepresent their identity, role, or affiliation with any School while using the Platform;
8. Harass, bully, or threaten any other User, including fellow students, teachers, or staff, through the Platform's communication tools.

Violation of this Section may result in immediate suspension or termination of access, without prejudice to SuperLMS's right to pursue legal remedies.
TXT],

            ['head' => 'Fees, Subscription, and Payment Terms', 'desc' => <<<'TXT'
1. Access to certain features of the Platform is subject to a Subscription fee, as agreed between SuperLMS and the Institutional Client in the applicable Service Agreement/Order Form.
2. Fees are payable in advance for the applicable Subscription period (annual/term-wise, as agreed), and are exclusive of applicable taxes (GST) unless otherwise stated.
3. Online payments (including student fee collection facilitated through the Platform) are processed via secure, RBI-authorised third-party payment gateways (e.g., Razorpay or equivalent). SuperLMS does not store complete card/bank credentials on its servers.
4. Fees once paid are generally non-refundable, except as expressly provided in the Service Agreement or as required under the Consumer Protection Act, 2019 and rules thereunder.
5. In case of non-payment of Subscription fees, SuperLMS reserves the right to suspend access to the Platform after providing reasonable prior notice to the Institutional Client.
6. SuperLMS is not responsible for any delay, failure, or reversal of payment transactions caused by the payment gateway, bank, or Users' own financial institution.
TXT],

            ['head' => 'Intellectual Property Rights', 'desc' => <<<'TXT'
1. All intellectual property rights in the Platform, including its software, source code, design, trademarks ("SuperLMS" name and logo), user interface, and underlying technology, are owned exclusively by Super Learnings Private Limited and are protected under the Copyright Act, 1957, the Trade Marks Act, 1999, and other applicable intellectual property laws.
2. Subject to compliance with these Terms, SuperLMS grants Institutional Clients and their Authorised Users a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform solely for internal educational and administrative purposes.
3. Content uploaded by Schools, teachers, or students (e.g., question banks, assignments, school branding/logo) remains the property of the respective uploading party. By uploading such Content, the uploading party grants SuperLMS a limited licence to host, store, process, and display such Content solely for the purpose of providing the Services.
4. Users shall not copy, modify, distribute, sell, or lease any part of the Platform, nor shall they reverse-engineer or attempt to extract its source code, except as expressly permitted by applicable law.
TXT],

            ['head' => 'Data Protection and Privacy', 'desc' => <<<'TXT'
The collection, use, storage, and processing of Personal Data through the Platform is governed by Our Privacy Policy (available at superlms.in/web/privacy), which is incorporated by reference into these Terms. Our data-handling practices are aligned with the Digital Personal Data Protection Act, 2023, the Information Technology Act, 2000, the IT (Reasonable Security Practices) Rules, 2011, and other applicable Indian data protection laws. By using the Platform, Users acknowledge that they have read and understood the Privacy Policy.
TXT],

            ['head' => 'Third-Party Services and Links', 'desc' => <<<'TXT'
The Platform may integrate with or link to third-party services, including payment gateways, video-conferencing tools (Zoom, Google Meet), communication service providers (SMS/WhatsApp Business API/Email), and cloud infrastructure providers. SuperLMS does not control and is not responsible for the content, privacy practices, availability, or performance of such third-party services. Use of any third-party service is subject to that third party's own terms and privacy policy.
TXT],

            ['head' => 'Service Availability and Disclaimer of Warranties', 'desc' => <<<'TXT'
1. SuperLMS strives to ensure the Platform is available and operational at all times but does not guarantee uninterrupted, error-free, or timely access. Scheduled maintenance, upgrades, or unforeseen technical issues may result in temporary unavailability.
2. The Platform is provided on an "as is" and "as available" basis. To the maximum extent permitted under applicable law, SuperLMS disclaims all warranties, whether express or implied, including warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement.
3. SuperLMS does not warrant that the Platform will meet every specific requirement of an Institutional Client or that AI-generated content will be free of errors.
TXT],

            ['head' => 'Limitation of Liability', 'desc' => <<<'TXT'
1. To the maximum extent permitted under applicable law, SuperLMS's aggregate liability arising out of or in connection with these Terms or the use of the Platform shall not exceed the total Subscription fees paid by the concerned Institutional Client in the twelve (12) months preceding the event giving rise to the claim.
2. SuperLMS shall not be liable for any indirect, incidental, consequential, special, or punitive damages, including loss of data, loss of revenue, or loss of academic records, arising out of or in connection with the use of, or inability to use, the Platform.
3. SuperLMS shall not be liable for any unauthorised access to or alteration of Users' data resulting from circumstances beyond its reasonable control, including but not limited to Force Majeure Events, third-party breaches, or User negligence in safeguarding login credentials.
4. Nothing in these Terms shall limit or exclude SuperLMS's liability for fraud, wilful misconduct, or gross negligence, or for any liability that cannot be excluded under applicable Indian law.
TXT],

            ['head' => 'Indemnification', 'desc' => <<<'TXT'
Each Institutional Client and Authorised User agrees to indemnify, defend, and hold harmless Super Learnings Private Limited, its directors, employees, and affiliates, from and against any claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising out of:
1. Breach of these Terms by the Institutional Client or its Authorised Users;
2. Any Content uploaded by the Institutional Client or its Authorised Users that infringes the intellectual property, privacy, or other rights of any third party;
3. Failure to obtain necessary consents from students, parents, or staff prior to onboarding onto the Platform; or
4. Any unlawful or unauthorised use of the Platform by the Institutional Client or its Authorised Users.
TXT],

            ['head' => 'Suspension and Termination', 'desc' => <<<'TXT'
1. SuperLMS may suspend or terminate access to the Platform, in whole or in part, immediately and without prior notice, in cases of: (a) material breach of these Terms; (b) non-payment of Subscription fees; (c) unlawful, fraudulent, or harmful use of the Platform; or (d) as required to comply with applicable law or a court/government order.
2. An Institutional Client may terminate its Subscription in accordance with the notice period specified in the applicable Service Agreement.
3. Upon termination, the Institutional Client's right to access the Platform shall cease immediately; however, obligations relating to payment, confidentiality, indemnification, and data retention (as set out in Our Privacy Policy) shall survive termination.
4. Upon termination, SuperLMS shall retain institutional data for a reasonable transition period to enable data export/migration by the Institutional Client, after which such data shall be deleted or anonymised in accordance with Our Privacy Policy, unless a longer retention period is legally mandated.
TXT],

            ['head' => 'Grievance Redressal', 'desc' => <<<'TXT'
In accordance with the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, and the Consumer Protection (E-Commerce) Rules, 2020 (to the extent applicable), SuperLMS has designated a Grievance Officer to address User concerns relating to these Terms:

Grievance Officer
Super Learnings Private Limited
Email: support@superlms.in
Phone: +91 9084748563
Address: Office No. 02, Braj Vihar Colony, Jattari, Khair, Aligarh, Uttar Pradesh – 202137
Business Hours: Monday–Saturday, 10:00 AM – 6:00 PM (IST)

Grievances shall be acknowledged within 48 hours and endeavoured to be resolved within 30 days of receipt.
TXT],

            ['head' => 'Force Majeure', 'desc' => <<<'TXT'
SuperLMS shall not be liable for any failure or delay in performing its obligations under these Terms where such failure or delay arises from circumstances beyond its reasonable control, including but not limited to acts of God, natural disasters, war, civil unrest, epidemic/pandemic, governmental action, internet/telecommunication outages, power failure, or failure of third-party service providers ("Force Majeure Event").
TXT],

            ['head' => 'Amendments to These Terms', 'desc' => <<<'TXT'
SuperLMS reserves the right to modify, update, or amend these Terms at any time, to reflect changes in law, regulatory requirements, or Our business practices. Material changes shall be communicated to Institutional Clients and Users via website notice, email, or in-app/dashboard notification. Continued use of the Platform following such changes shall constitute acceptance of the amended Terms. Users are encouraged to review these Terms periodically.
TXT],

            ['head' => 'Assignment', 'desc' => <<<'TXT'
Users shall not assign or transfer their rights or obligations under these Terms without SuperLMS's prior written consent. SuperLMS may assign these Terms, in whole or in part, to any affiliate or successor entity, including in connection with a merger, acquisition, or sale of assets, provided that such assignment does not materially diminish the rights of Users under these Terms.
TXT],

            ['head' => 'Severability', 'desc' => <<<'TXT'
If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such provision shall be severed, and the remaining provisions shall continue in full force and effect.
TXT],

            ['head' => 'Entire Agreement', 'desc' => <<<'TXT'
These Terms, together with Our Privacy Policy and any applicable Service Agreement/Order Form executed between SuperLMS and an Institutional Client, constitute the entire agreement between the parties with respect to the subject matter hereof, and supersede all prior discussions, negotiations, and agreements, whether written or oral.
TXT],

            ['head' => 'Governing Law and Dispute Resolution', 'desc' => <<<'TXT'
1. These Terms shall be governed by and construed in accordance with the laws of India.
2. Any dispute, controversy, or claim arising out of or in connection with these Terms shall first be attempted to be resolved amicably through good-faith negotiation between the parties.
3. Failing amicable resolution within thirty (30) days, the dispute shall be referred to arbitration under the Arbitration and Conciliation Act, 1996, to be conducted by a sole arbitrator mutually appointed by the parties, with the seat and venue of arbitration at Aligarh, Uttar Pradesh, and the proceedings conducted in the English language.
4. Subject to the above, the courts at Aligarh, Uttar Pradesh shall have exclusive jurisdiction over any matters not referred to arbitration or in aid of arbitral proceedings (e.g., interim relief).
TXT],

            ['head' => 'How Schools and Users Are Bound by These Terms', 'desc' => <<<'TXT'
1. Schools, upon signing the Service Agreement/Order Form and creating an Admin account, are deemed to have accepted these Terms on behalf of the institution.
2. Teachers and Staff, upon receiving login credentials from the School Admin, are required to accept these Terms and the Privacy Policy at first login before gaining access to the Platform.
3. Parents/Guardians, upon providing consent at the time of their child's admission/onboarding and activating their Parent Portal login, are deemed to have accepted these Terms on their own behalf and, where applicable, on behalf of their child.
4. Students, where granted supervised access to the Student Dashboard, use the Platform subject to these Terms as accepted by their School and parent/guardian on their behalf.
5. Any individual using self-registration (where enabled) must affirmatively accept these Terms and the Privacy Policy via checkbox/OTP-verified confirmation before account activation.
TXT],

            ['head' => 'Conclusion', 'desc' => <<<'TXT'
These Terms and Conditions are designed to ensure a safe, transparent, and legally compliant environment for every School, Teacher, Student, and Parent using SuperLMS. By clearly defining the rights and responsibilities of Schools (as Institutional Clients), Authorised Users, and SuperLMS itself, these Terms aim to:
• Protect the interests and data of students and staff;
• Ensure fair, lawful, and transparent use of the Platform by all stakeholders;
• Clarify payment, subscription, and cancellation terms for Institutional Clients;
• Set out clear boundaries around intellectual property, liability, and dispute resolution; and
• Provide an accessible grievance redressal mechanism for any User with concerns.

We encourage all Schools, Teachers, Students, and Parents to read these Terms carefully alongside Our Privacy Policy before using the Platform, and to reach out to Us at support@superlms.in with any questions. SuperLMS remains committed to maintaining these Terms in line with evolving Indian law, including the Digital Personal Data Protection Act, 2023, the Consumer Protection Act, 2019, and applicable education sector regulations, so that trust and compliance remain at the core of every School's experience with the Platform.
TXT],

            ['head' => 'Contact Us', 'desc' => <<<'TXT'
For any questions, concerns, or requests regarding these Terms and Conditions, please contact:

Super Learnings Private Limited
Email: support@superlms.in
Phone: +91 9084748563
Address: Office No. 02, Braj Vihar Colony, Jattari, Khair, Aligarh, Uttar Pradesh – 202137
Business Hours: Monday–Saturday, 10:00 AM – 6:00 PM (IST)
TXT],
        ];
    }
};
