<?php

return [
    'admin' => [
        [
            'title' => 'Quick Links',
            'link' => 'admin.quick-links',
            'icon' => 'link',
            'prefix' => 'admin.quick-links',
        ],
        [
            'title' => 'Home',
            'link' => 'admin.home',
            'icon' => 'home',
            'prefix' => 'admin.home',
        ],
        [
            'title' => 'Analytics',
            'link' => 'admin.analytics',
            'icon' => 'chart-bar',
            'prefix' => 'admin.analytics',
        ],
        [
            'title' => 'Standard',
            'link' => 'admin.standard',
            'icon' => 'book-open',
            'prefix' => 'admin.standard',
        ],
        [
            'title' => 'Students',
            'link' => 'admin.student',
            'icon' => 'users',
            'prefix' => 'admin.student',
        ],
        [
            'title' => 'Teachers',
            'link' => 'admin.teacher',
            'icon' => 'user',
            'prefix' => 'admin.teacher',
        ],
        [
            'title' => 'Fees',
            'link' => 'admin.fee',
            'icon' => 'currency-rupee',
            'prefix' => 'admin.fee',
        ],
        [
            'title' => 'Ledger',
            'link' => 'admin.ledger',
            'icon' => 'calculator',
            'prefix' => 'admin.ledger',
        ],
        [
            'title' => 'Payroll',
            'link' => 'admin.payroll',
            'icon' => 'banknotes',
            'prefix' => 'admin.payroll',
        ],
        [
            'title' => 'Credit',
            'link' => 'admin.credit',
            'icon' => 'credit-card',
            'prefix' => 'admin.credit',
        ],
        [
            'title' => 'Attendance',
            'link' => 'admin.attendance',
            'icon' => 'check-circle',
            'prefix' => 'admin.attendance',
        ],
        [
            'title' => 'Transportation',
            'link' => 'admin.transport',
            'icon' => 'truck',
            'prefix' => 'admin.transport',
        ],
        [
            'title' => 'Homework',
            'link' => 'admin.homework',
            'icon' => 'pencil',
            'prefix' => 'admin.homework',
        ],
        [
            'title' => 'Time Table',
            'link' => 'admin.timetable',
            'icon' => 'calendar',
            'prefix' => 'admin.timetable',
        ],
        [
            'title' => 'Arrangement',
            'link' => 'admin.arrangement',
            'icon' => 'table-cells',
            'prefix' => 'admin.arrangement',
        ],
        [
            'title' => 'Announcement',
            'link' => 'admin.announcement',
            'icon' => 'speaker-wave',
            'prefix' => 'admin.announcement',
        ],
        [
            'title' => 'Calender',
            'link' => 'admin.calender',
            'icon' => 'calendar',
            'prefix' => 'admin.calender',
        ],
        [
            'title' => 'Syllabus',
            'link' => 'admin.syllabus',
            'icon' => 'building-library',
            'prefix' => 'admin.syllabus',
        ],
        [
            'title' => 'Content',
            'link' => 'admin.content',
            'icon' => 'document',
            'prefix' => 'admin.content',
        ],
        [
            'title' => 'Quiz',
            'link' => 'admin.quiz',
            'icon' => 'question-mark-circle',
            'prefix' => 'admin.quiz',
        ],
        [
            'title' => 'Book',
            'link' => 'admin.book',
            'icon' => 'book-open',
            'prefix' => 'admin.book',
        ],
        [
            'title' => 'Enquiries',
            'link' => 'admin.enqueries',
            'icon' => 'question-mark-circle',
            'prefix' => 'admin.enqueries',
        ],
        [
            'title' => 'ID Card',
            'link' => 'admin.id-card',
            'icon' => 'identification',
            'prefix' => 'admin.id-card',
        ],
        [
            'title' => 'Exam',
            'link' => 'admin.add-exam',
            'icon' => 'paper-clip',
            'prefix' => 'admin.add-exam',
        ],
        [
            'title' => 'Admit Card',
            'link' => 'admin.admit-card',
            'icon' => 'ticket',
            'prefix' => 'admin.admit-card',
        ],
        [
            'title' => 'Seating Plan',
            'link' => 'admin.seating-plan',
            'icon' => 'view-columns',
            'prefix' => 'admin.seating-plan',
        ],
        [
            'title' => 'Performance',
            'link' => 'admin.performance',
            'icon' => 'arrow-trending-up',
            'prefix' => 'admin.performance',
        ],
        [
            'title' => 'Exam Copy',
            'link' => 'admin.exam-copy',
            'icon' => 'document-text',
            'prefix' => 'admin.exam-copy',
        ],
        [
            'title' => 'Report Card',
            'link' => 'admin.report-card',
            'icon' => 'document-duplicate',
            'prefix' => 'admin.report-card',
        ],
        [
            'title' => 'TC & Certificate',
            'link' => 'admin.tc-certificate',
            'icon' => 'document-arrow-down',
            'prefix' => 'admin.tc-certificate',
        ],
        [
            'title' => 'More',
            'link' => 'admin.more',
            'icon' => 'squares-2x2',
            'prefix' => 'admin.more',
        ],
    ],

    'super-admin' => [
        [
            'title' => 'Quick Links',
            'link' => 'super-admin.quick-links',
            'icon' => 'link',
            'prefix' => 'super-admin.quick-links',
        ],
        [
            'title' => 'Home',
            'link' => 'super-admin.dashboard',
            'icon' => 'home',
            'prefix' => 'super-admin.dashboard',
        ],
        [
            'title' => 'Analytics',
            'link' => 'super-admin.analytics',
            'icon' => 'chart-bar',
            'prefix' => 'super-admin.analytics',
        ],
        [
            'title' => 'Reports',
            'link' => 'super-admin.reports',
            'icon' => 'document-text',
            'prefix' => 'super-admin.reports',
        ],
        [
            'title' => 'Schools',
            'link' => 'super-admin.schools',
            'icon' => 'building-library',
            'prefix' => 'super-admin.schools',
        ],
        [
            'title' => 'Students',
            'link' => 'super-admin.students',
            'icon' => 'users',
            'prefix' => 'super-admin.students',
        ],
        [
            'title' => 'Teachers',
            'link' => 'super-admin.teachers',
            'icon' => 'academic-cap',
            'prefix' => 'super-admin.teachers',
        ],
        [
            'title' => 'Fees',
            'link' => 'super-admin.fees',
            'icon' => 'banknotes',
            'prefix' => 'super-admin.fees',
        ],
        [
            'title' => 'Users',
            'link' => 'super-admin.users',
            'icon' => 'user-group',
            'prefix' => 'super-admin.users',
        ],
        [
            'title' => 'Payroll',
            'link' => 'super-admin.payroll',
            'icon' => 'banknotes',
            'prefix' => 'super-admin.payroll',
        ],
        [
            'title' => 'Push Notification',
            'link' => 'super-admin.push-notification',
            'icon' => 'megaphone',
            'prefix' => 'super-admin.push-notification',
        ],
        [
            'title' => 'Credit',
            'link' => 'super-admin.credit',
            'icon' => 'credit-card',
            'prefix' => 'super-admin.credit',
        ],
        [
            'title' => 'Support',
            'link' => 'super-admin.support',
            'icon' => 'question-mark-circle',
            'prefix' => 'super-admin.support',
        ],
        [
            'title' => 'Enquiries',
            'link' => 'super-admin.enquiries',
            'icon' => 'chat-bubble-oval-left-ellipsis',
            'prefix' => 'super-admin.enquiries',
        ],
        // [
        //     'title' => 'Sessions',
        //     'link' => 'super-admin.sessions',
        //     'icon' => 'square-3-stack-3d',
        //     'prefix' => 'super-admin.sessions',
        // ],
        [
            'title' => 'Terms & Conditions',
            'link' => 'super-admin.terms-condition',
            'icon' => 'document-text',
            'prefix' => 'super-admin.terms-condition',
        ],
        // [
        //     'title' => 'Website Data',
        //     'link' => 'super-admin.website-data',
        //     'icon' => 'bookmark-square',
        //     'prefix' => 'super-admin.website-data',
        // ],
        [
            'title' => 'Terms Of Use',
            'link' => 'super-admin.term-of-use',
            'icon' => 'command-line',
            'prefix' => 'super-admin.term-of-use',
        ],
        [
            'title' => 'Privacy Policy',
            'link' => 'super-admin.privacy-policy',
            'icon' => 'lock-closed',
            'prefix' => 'super-admin.privacy-policy',
        ],
        [
            'title' => 'Rating',
            'link' => 'super-admin.rating',
            'icon' => 'star',
            'prefix' => 'super-admin.rating',
        ],
        [
            'title' => 'About App',
            'link' => 'super-admin.about-app',
            'icon' => 'archive-box',
            'prefix' => 'super-admin.about-app',
        ],
        [
            'title' => 'School Website',
            'link' => 'super-admin.portal-website',
            'icon' => 'globe-alt',
            'prefix' => 'super-admin.portal-website',
        ],

        // ── Dynamic marketing pages (footer "Company" section) ──
        [
            'title' => 'Careers',
            'link' => 'super-admin.website.careers',
            'icon' => 'briefcase',
            'prefix' => 'super-admin.website.careers',
        ],
        [
            'title' => 'Become Executive',
            'link' => 'super-admin.website.become-executive',
            'icon' => 'user-plus',
            'prefix' => 'super-admin.website.become-executive',
        ],
        [
            'title' => 'Blogs',
            'link' => 'super-admin.website.blogs',
            'icon' => 'newspaper',
            'prefix' => 'super-admin.website.blogs',
        ],
        [
            'title' => 'FAQs',
            'link' => 'super-admin.website.faqs',
            'icon' => 'question-mark-circle',
            'prefix' => 'super-admin.website.faqs',
        ],

    ],

    'accounts' => [
        [
            'title' => 'Dashboard',
            'link' => 'accounts.dashboard',
            'icon' => 'home',
            'prefix' => 'accounts.dashboard',
        ],
        [
            'title' => 'Payroll',
            'link' => 'accounts.payroll',
            'icon' => 'banknotes',
            'prefix' => 'accounts.payroll',
        ],
        [
            'title' => 'Credit',
            'link' => 'accounts.credit',
            'icon' => 'credit-card',
            'prefix' => 'accounts.credit',
        ],
        [
            'title' => 'Admissions',
            'link' => 'accounts.admissions',
            'icon' => 'user-plus',
            'prefix' => 'accounts.admissions',
        ],
        [
            'title' => 'Fee Submission',
            'link' => 'accounts.fee-submission',
            'icon' => 'currency-rupee',
            'prefix' => 'accounts.fee-submission',
        ],
        [
            'title' => 'View Fee',
            'link' => 'accounts.view-fee',
            'icon' => 'eye',
            'prefix' => 'accounts.view-fee',
        ],
        [
            'title' => 'Fee Structure',
            'link' => 'accounts.fee-structure',
            'icon' => 'table-cells',
            'prefix' => 'accounts.fee-structure',
        ],
        [
            'title' => 'Payments',
            'link' => 'accounts.payments',
            'icon' => 'banknotes',
            'prefix' => 'accounts.payments',
        ],
        [
            'title' => 'Penalties',
            'link' => 'accounts.penalties',
            'icon' => 'exclamation-triangle',
            'prefix' => 'accounts.penalties',
        ],
        [
            'title' => 'Fee Cycles',
            'link' => 'accounts.fee-cycles',
            'icon' => 'arrow-path',
            'prefix' => 'accounts.fee-cycles',
        ],
        [
            'title' => 'Attendance',
            'link' => 'accounts.attendance',
            'icon' => 'check-circle',
            'prefix' => 'accounts.attendance',
        ],
        [
            'title' => 'Transport',
            'link' => 'accounts.transport',
            'icon' => 'truck',
            'prefix' => 'accounts.transport',
        ],
        [
            'title' => 'Calendar',
            'link' => 'accounts.calendar',
            'icon' => 'calendar',
            'prefix' => 'accounts.calendar',
        ],
        [
            'title' => 'ID Card',
            'link' => 'accounts.id-card',
            'icon' => 'identification',
            'prefix' => 'accounts.id-card',
        ],
        [
            'title' => 'Admit Card',
            'link' => 'accounts.admit-card',
            'icon' => 'ticket',
            'prefix' => 'accounts.admit-card',
        ],
        [
            'title' => 'Report Card',
            'link' => 'accounts.report-card',
            'icon' => 'document-duplicate',
            'prefix' => 'accounts.report-card',
        ],
        [
            'title' => 'TC & Certificates',
            'link' => 'accounts.tc-certificate',
            'icon' => 'document-arrow-down',
            'prefix' => 'accounts.tc-certificate',
        ],
    ],

];
